version: "3.9"

services:
  backend:
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend-store:
    volumes:
      - ./frontend-store:/app
      - /app/node_modules

  frontend-admin:
    volumes:
      - ./frontend-admin:/app
      - /app/node_modules
