version: "3.9"

services:
  backend:
    build:
      context: ./backend
      target: runtime
    container_name: ecommerce_backend
    restart: always
    environment:
      NODE_ENV: production
    command: ["npm", "start"]
    ports:
      - "5005:5005"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - .env
    networks:
      - ecommerce_net

  frontend-store:
    build:
      context: ./frontend-store
      target: build
    container_name: ecommerce_frontend_store
    restart: always
    command: >
      sh -c "npm run build && npx vite preview --host 0.0.0.0 --port 3000"
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    networks:
      - ecommerce_net

  frontend-admin:
    build:
      context: ./frontend-admin
      target: build
    container_name: ecommerce_frontend_admin
    restart: always
    command: >
      sh -c "npm run build && npx vite preview --host 0.0.0.0 --port 3000"
    ports:
      - "3001:3000"
    environment:
      NODE_ENV: production
    networks:
      - ecommerce_net

  mysql:
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ecommerce_net

  redis:
    restart: always
    networks:
      - ecommerce_net

  phpmyadmin:
    restart: always
    ports:
      - "8080:80"
    networks:
      - ecommerce_net

volumes:
  mysql_data:
  redis_data:

networks:
  ecommerce_net:
    external: false
